name: Publish to pub.dev

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # For OIDC authentication
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Adjust as needed

      - name: Install Dart package dependencies
        run: dart pub get

      - name: Validate Flutter example
        run: |
          cd example
          flutter pub get
          cd ..

      - name: Publish to pub.dev
        run: dart pub publish --force --no-example
