name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*" # e.g., v1.0.0, v2.1.3-beta

  workflow_dispatch:

jobs:
  publish:
    permissions:
      id-token: write   # Required for OIDC-based publishing
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
